# Generated by Django 5.0.6 on 2024-07-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='category_id',
            new_name='Category_Id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='Transaction_Date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='Transaction_Type',
        ),
    ]
