# Generated by Django 5.0.6 on 2024-07-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_description_transaction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Category_Id',
            new_name='CategoryID',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_Date',
            new_name='TransactionDate',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_Type',
            new_name='TransactionType',
        ),
    ]
